
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/layout/Footer";
import Navbar from "./components/layout/Navbar";
// import HomePage from "./content";
 // ✅ path ที่ถูก (components อยู่ใน app)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}suppressHydrationWarning={true}
      >
        {/* ทำ layout ทั้งหน้าจอ */}
        <div className="flex min-h-screen flex-col">
          {/* Navbar อยู่ด้านบนทุกหน้า */}
          <Navbar />
          
          {/* พื้นที่เนื้อหาหน้าแต่ละหน้า */}
          <main className="flex-1 pt-10 md:pt-[100px] lg:pt-[120px]">
            {children}
          </main>
          
          {/* Footer ล่างสุดทุกหน้า */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
