<<<<<<< HEAD
import { PrimaryButton, CancelButton } from "./components/ui/Button";

export default function Home(){
  return (
    <div className="flex gap-5 p-5  ">
      <PrimaryButton >ยืนยัน</PrimaryButton>
      <CancelButton>ยกเลิก</CancelButton>
      
    </div>
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/layout/Footer";
 // ✅ path ที่ถูก (components อยู่ใน app)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ทำ layout ทั้งหน้าจอ */}
        <div className="flex min-h-screen flex-col">
          {/* พื้นที่เนื้อหาหน้าแต่ละหน้า */}
          <main className="flex-1">{children}</main>

          {/* Footer ล่างสุดทุกหน้า */}
          <Footer />
        </div>
      </body>
    </html>
>>>>>>> cf25cc46882a7d5c7d4009660fa69b187aa6f7f0
  );
}
